import type { Metadata } from "next";
//import localFont from "next/font/local";
import "./globals.css";
import { ThemeProvider } from "@/src/theme/ThemeProvider";
import clsx from "clsx";
import { Header } from "@/src/features/layout/Header";
import { Footer } from "@/src/features/layout/Footer";

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

//geistSans.variable, geistMono.variable,

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className='h-full'>
      <body

        className={clsx( 'bg-background h-full')}>
        <ThemeProvider attribute= 'class' defaultTheme="system" enableSystem>
          <div className="flex flex-col h-full">
            <Header/>
            <div className="flex-1 max-w-lg m-auto py-14 w-full"> {children} </div>
           < Footer/>
          </div>
      </ThemeProvider>
      </body>
    </html>
  );
}
